# Generated by Django 4.0.2 on 2022-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealicious', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='number',
            field=models.IntegerField(default=''),
        ),
    ]
