# Generated by Django 4.0.2 on 2022-04-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tealicious', '0002_alter_contact_number_alter_event_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
